# -*- coding: utf-8 -*-

'''
Created on Dec 8, 2015

@author: aaronhu
'''
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob
import py2exe


# APP = ['screen.py']
# DATA_FILES = ['data','game_music']
# OPTIONS = {'argv_emulation': True,
#            'iconfile': '/Users/aaronhu/Documents/workspace/difinitives/data/icon.png',
#            'plist': {
#             'CFBundleIconFile': "icon.png",
#             'CFBundleGetInfoString': "Definitives",
#             'CFBundleIdentifier': "com.ualberta.augustana.AUCSC220.Aaron Hu",
#             'CFBundleVersion': "0.1.0 beta release",
#             'CFBundleShortVersionString': "0.1.0_beta_15/12/8",
#             'NSHumanReadableCopyright': u"Copyright © 2015, Aaron Hu, All Rights Reserved",
#        }
#            }

data_files = [("Microsoft.VC90.CRT", glob(r'C:\Program Files\Microsoft Visual Studio 9.0\VC\redist\x86\Microsoft.VC90.CRT\*.*'))]
  setup(
    console=[screen.py]
    data_files=data_files,
    etc
  )
# setup(
#     app=APP,
#     data_files=DATA_FILES,
#     options={'py2app': OPTIONS},
#     setup_requires=['py2app'],
# )
